# Generated by Django 3.2.5 on 2021-08-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210817_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100, null=True)),
                ('hsnCode', models.IntegerField(null=True)),
                ('defaultPrice', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('unitRate', models.FloatField(null=True)),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
        ),
    ]
