# Generated by Django 3.2.5 on 2021-08-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_invoiceproducts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='id',
            new_name='invoiceId',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
