# Generated by Django 3.2.5 on 2021-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='product',
            field=models.ManyToManyField(null=True, to='api.Product'),
        ),
    ]
