# Generated by Django 3.2.5 on 2021-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210818_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproducts',
            name='product',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
