# Generated by Django 3.2.5 on 2021-08-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_invoiceproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_products', to='api.invoice'),
        ),
    ]
