# Generated by Django 3.2.5 on 2021-08-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_invoiceproducts_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
    ]
